services:
  # $ docker run --name some-redis -d redis
  go-redis:
    container_name:  go-redis
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - go-redis:/data
    expose:
      - 6379
    networks:
      - go-network

  # docker run --name go-elastic --net elastic -p 9200:9200 -it -m 1GB docker.elastic.co/elasticsearch/elasticsearch:9.4.2
  # docker exec -it go-elastic /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic
  # docker exec -it go-elastic /usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token -s kibana
  # docker exec go-elastic  cat /usr/share/elasticsearch/config/certs/http_ca.crt | openssl x509 -fingerprint -sha256 -noout
  go-elastic:
    container_name: go-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.2
    volumes:
      - go-elastic:/usr/share/elasticsearch/data
    expose:
      - 9200
    mem_limit: 1g
    networks:
      - go-network

  # docker run --name kib01 --net elastic -p 5601:5601 docker.elastic.co/kibana/kibana:9.4.2
  go-kibana:
    container_name: go-kibana
    image: docker.elastic.co/kibana/kibana:9.4.2
    ports:
      - 5601:5601
    networks:
      - go-network

  # $ docker run --detach --hostname my-rabbit --name some-rabbit \
  #     --env RABBITMQ_DEFAULT_USER=user \
  #     --env RABBITMQ_DEFAULT_PASS=password \
  #     --publish 15672:15672 \
  #     --publish 5672:5672 \
  #      rabbitmq:management
  go-rabbitmq:
    container_name: go-rabbitmq
    image: rabbitmq:management
    volumes:
      - go-rabbitmq:/var/lib/rabbitmq
    expose:
      - 15672
      - 5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - go-network

  # $ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag
  go-mysql:
    container_name: go-mysql
    image: mysql:latest
    volumes:
      - go-mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - go-network
    
  go-backend:
    container_name: go-backend
    image: img-go-backend:latest
    expose:
      - 3069
    env_file:
      - .env.production
    networks:
      - go-network
    depends_on:
      - go-redis
      - go-elastic
      - go-rabbitmq
      - go-mysql


  # docker exec go-nginx nginx -t
  # docker exec go-nginx nginx -s reload
  go-nginx:
    container_name: go-nginx
    image: nginx:1.27-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./data/nginx/certs:/etc/nginx/certs:ro
    networks:
      - go-network

networks:
  go-network:
    external: true

volumes:
  go-redis:
  go-elastic:
  go-rabbitmq:
  go-mysql: