// Code generated by ent, DO NOT EDIT.

package chatmessages

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the chatmessages type in the database.
	Label = "chat_messages"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldChatGroupID holds the string denoting the chat_group_id field in the database.
	FieldChatGroupID = "chat_group_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldMessageText holds the string denoting the message_text field in the database.
	FieldMessageText = "message_text"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeChatGroups holds the string denoting the chatgroups edge name in mutations.
	EdgeChatGroups = "ChatGroups"
	// EdgeUsers holds the string denoting the users edge name in mutations.
	EdgeUsers = "Users"
	// Table holds the table name of the chatmessages in the database.
	Table = "chat_messages"
	// ChatGroupsTable is the table that holds the ChatGroups relation/edge.
	ChatGroupsTable = "chat_messages"
	// ChatGroupsInverseTable is the table name for the ChatGroups entity.
	// It exists in this package in order to avoid circular dependency with the "chatgroups" package.
	ChatGroupsInverseTable = "chat_groups"
	// ChatGroupsColumn is the table column denoting the ChatGroups relation/edge.
	ChatGroupsColumn = "chat_group_id"
	// UsersTable is the table that holds the Users relation/edge.
	UsersTable = "chat_messages"
	// UsersInverseTable is the table name for the Users entity.
	// It exists in this package in order to avoid circular dependency with the "users" package.
	UsersInverseTable = "users"
	// UsersColumn is the table column denoting the Users relation/edge.
	UsersColumn = "user_id"
)

// Columns holds all SQL columns for chatmessages fields.
var Columns = []string{
	FieldID,
	FieldDeletedAt,
	FieldChatGroupID,
	FieldUserID,
	FieldMessageText,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-backend/ent/runtime"
var (
	Hooks        [2]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the ChatMessages queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByChatGroupID orders the results by the chat_group_id field.
func ByChatGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatGroupID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByMessageText orders the results by the message_text field.
func ByMessageText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageText, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByChatGroupsField orders the results by ChatGroups field.
func ByChatGroupsField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatGroupsStep(), sql.OrderByField(field, opts...))
	}
}

// ByUsersField orders the results by Users field.
func ByUsersField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUsersStep(), sql.OrderByField(field, opts...))
	}
}
func newChatGroupsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatGroupsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChatGroupsTable, ChatGroupsColumn),
	)
}
func newUsersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UsersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
	)
}
