// Code generated by ent, DO NOT EDIT.

package chatmessages

import (
	"go-backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldDeletedAt, v))
}

// ChatGroupID applies equality check predicate on the "chat_group_id" field. It's identical to ChatGroupIDEQ.
func ChatGroupID(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldChatGroupID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldUserID, v))
}

// MessageText applies equality check predicate on the "message_text" field. It's identical to MessageTextEQ.
func MessageText(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldMessageText, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotNull(FieldDeletedAt))
}

// ChatGroupIDEQ applies the EQ predicate on the "chat_group_id" field.
func ChatGroupIDEQ(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldChatGroupID, v))
}

// ChatGroupIDNEQ applies the NEQ predicate on the "chat_group_id" field.
func ChatGroupIDNEQ(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldChatGroupID, v))
}

// ChatGroupIDIn applies the In predicate on the "chat_group_id" field.
func ChatGroupIDIn(vs ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldChatGroupID, vs...))
}

// ChatGroupIDNotIn applies the NotIn predicate on the "chat_group_id" field.
func ChatGroupIDNotIn(vs ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldChatGroupID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldUserID, vs...))
}

// MessageTextEQ applies the EQ predicate on the "message_text" field.
func MessageTextEQ(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldMessageText, v))
}

// MessageTextNEQ applies the NEQ predicate on the "message_text" field.
func MessageTextNEQ(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldMessageText, v))
}

// MessageTextIn applies the In predicate on the "message_text" field.
func MessageTextIn(vs ...string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldMessageText, vs...))
}

// MessageTextNotIn applies the NotIn predicate on the "message_text" field.
func MessageTextNotIn(vs ...string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldMessageText, vs...))
}

// MessageTextGT applies the GT predicate on the "message_text" field.
func MessageTextGT(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGT(FieldMessageText, v))
}

// MessageTextGTE applies the GTE predicate on the "message_text" field.
func MessageTextGTE(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGTE(FieldMessageText, v))
}

// MessageTextLT applies the LT predicate on the "message_text" field.
func MessageTextLT(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLT(FieldMessageText, v))
}

// MessageTextLTE applies the LTE predicate on the "message_text" field.
func MessageTextLTE(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLTE(FieldMessageText, v))
}

// MessageTextContains applies the Contains predicate on the "message_text" field.
func MessageTextContains(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldContains(FieldMessageText, v))
}

// MessageTextHasPrefix applies the HasPrefix predicate on the "message_text" field.
func MessageTextHasPrefix(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldHasPrefix(FieldMessageText, v))
}

// MessageTextHasSuffix applies the HasSuffix predicate on the "message_text" field.
func MessageTextHasSuffix(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldHasSuffix(FieldMessageText, v))
}

// MessageTextEqualFold applies the EqualFold predicate on the "message_text" field.
func MessageTextEqualFold(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEqualFold(FieldMessageText, v))
}

// MessageTextContainsFold applies the ContainsFold predicate on the "message_text" field.
func MessageTextContainsFold(v string) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldContainsFold(FieldMessageText, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ChatMessages {
	return predicate.ChatMessages(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasChatGroups applies the HasEdge predicate on the "ChatGroups" edge.
func HasChatGroups() predicate.ChatMessages {
	return predicate.ChatMessages(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChatGroupsTable, ChatGroupsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatGroupsWith applies the HasEdge predicate on the "ChatGroups" edge with a given conditions (other predicates).
func HasChatGroupsWith(preds ...predicate.ChatGroups) predicate.ChatMessages {
	return predicate.ChatMessages(func(s *sql.Selector) {
		step := newChatGroupsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsers applies the HasEdge predicate on the "Users" edge.
func HasUsers() predicate.ChatMessages {
	return predicate.ChatMessages(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UsersTable, UsersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsersWith applies the HasEdge predicate on the "Users" edge with a given conditions (other predicates).
func HasUsersWith(preds ...predicate.Users) predicate.ChatMessages {
	return predicate.ChatMessages(func(s *sql.Selector) {
		step := newUsersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ChatMessages) predicate.ChatMessages {
	return predicate.ChatMessages(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ChatMessages) predicate.ChatMessages {
	return predicate.ChatMessages(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ChatMessages) predicate.ChatMessages {
	return predicate.ChatMessages(sql.NotPredicates(p))
}
