// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/articles"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ArticlesCreate is the builder for creating a Articles entity.
type ArticlesCreate struct {
	config
	mutation *ArticlesMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ArticlesCreate) SetDeletedAt(v time.Time) *ArticlesCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableDeletedAt(v *time.Time) *ArticlesCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ArticlesCreate) SetTitle(v string) *ArticlesCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ArticlesCreate) SetContent(v string) *ArticlesCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableContent(v *string) *ArticlesCreate {
	if v != nil {
		_c.SetContent(*v)
	}
	return _c
}

// SetImageURL sets the "image_url" field.
func (_c *ArticlesCreate) SetImageURL(v string) *ArticlesCreate {
	_c.mutation.SetImageURL(v)
	return _c
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableImageURL(v *string) *ArticlesCreate {
	if v != nil {
		_c.SetImageURL(*v)
	}
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *ArticlesCreate) SetLikeCount(v int) *ArticlesCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableLikeCount(v *int) *ArticlesCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetViews sets the "views" field.
func (_c *ArticlesCreate) SetViews(v int) *ArticlesCreate {
	_c.mutation.SetViews(v)
	return _c
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableViews(v *int) *ArticlesCreate {
	if v != nil {
		_c.SetViews(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ArticlesCreate) SetUserID(v int) *ArticlesCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ArticlesCreate) SetCreatedAt(v time.Time) *ArticlesCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableCreatedAt(v *time.Time) *ArticlesCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ArticlesCreate) SetUpdatedAt(v time.Time) *ArticlesCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ArticlesCreate) SetNillableUpdatedAt(v *time.Time) *ArticlesCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ArticlesMutation object of the builder.
func (_c *ArticlesCreate) Mutation() *ArticlesMutation {
	return _c.mutation
}

// Save creates the Articles in the database.
func (_c *ArticlesCreate) Save(ctx context.Context) (*Articles, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ArticlesCreate) SaveX(ctx context.Context) *Articles {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticlesCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticlesCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ArticlesCreate) defaults() error {
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := articles.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.Views(); !ok {
		v := articles.DefaultViews
		_c.mutation.SetViews(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if articles.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized articles.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := articles.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if articles.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized articles.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := articles.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ArticlesCreate) check() error {
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Articles.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := articles.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Articles.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "Articles.like_count"`)}
	}
	if _, ok := _c.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`ent: missing required field "Articles.views"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Articles.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Articles.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Articles.updated_at"`)}
	}
	return nil
}

func (_c *ArticlesCreate) sqlSave(ctx context.Context) (*Articles, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ArticlesCreate) createSpec() (*Articles, *sqlgraph.CreateSpec) {
	var (
		_node = &Articles{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(articles.Table, sqlgraph.NewFieldSpec(articles.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(articles.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(articles.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(articles.FieldContent, field.TypeString, value)
		_node.Content = &value
	}
	if value, ok := _c.mutation.ImageURL(); ok {
		_spec.SetField(articles.FieldImageURL, field.TypeString, value)
		_node.ImageURL = &value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(articles.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.Views(); ok {
		_spec.SetField(articles.FieldViews, field.TypeInt, value)
		_node.Views = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(articles.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(articles.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(articles.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ArticlesCreateBulk is the builder for creating many Articles entities in bulk.
type ArticlesCreateBulk struct {
	config
	err      error
	builders []*ArticlesCreate
}

// Save creates the Articles entities in the database.
func (_c *ArticlesCreateBulk) Save(ctx context.Context) ([]*Articles, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Articles, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ArticlesMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ArticlesCreateBulk) SaveX(ctx context.Context) []*Articles {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ArticlesCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ArticlesCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
