// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-backend/ent/chatmessages"
	"go-backend/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatMessagesDelete is the builder for deleting a ChatMessages entity.
type ChatMessagesDelete struct {
	config
	hooks    []Hook
	mutation *ChatMessagesMutation
}

// Where appends a list predicates to the ChatMessagesDelete builder.
func (_d *ChatMessagesDelete) Where(ps ...predicate.ChatMessages) *ChatMessagesDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ChatMessagesDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChatMessagesDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ChatMessagesDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(chatmessages.Table, sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ChatMessagesDeleteOne is the builder for deleting a single ChatMessages entity.
type ChatMessagesDeleteOne struct {
	_d *ChatMessagesDelete
}

// Where appends a list predicates to the ChatMessagesDelete builder.
func (_d *ChatMessagesDeleteOne) Where(ps ...predicate.ChatMessages) *ChatMessagesDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ChatMessagesDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{chatmessages.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ChatMessagesDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
