// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-backend/ent/chatgroups"
	"go-backend/ent/chatmessages"
	"go-backend/ent/users"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ChatMessages is the model entity for the ChatMessages schema.
type ChatMessages struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deletedAt"`
	// ChatGroupID holds the value of the "chat_group_id" field.
	ChatGroupID int `json:"chatGroupId"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"userId"`
	// MessageText holds the value of the "message_text" field.
	MessageText string `json:"messageText"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatMessagesQuery when eager-loading is set.
	Edges        ChatMessagesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatMessagesEdges holds the relations/edges for other nodes in the graph.
type ChatMessagesEdges struct {
	// ChatGroups holds the value of the ChatGroups edge.
	ChatGroups *ChatGroups `json:"ChatGroups,omitempty"`
	// Users holds the value of the Users edge.
	Users *Users `json:"Users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ChatGroupsOrErr returns the ChatGroups value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMessagesEdges) ChatGroupsOrErr() (*ChatGroups, error) {
	if e.ChatGroups != nil {
		return e.ChatGroups, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: chatgroups.Label}
	}
	return nil, &NotLoadedError{edge: "ChatGroups"}
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatMessagesEdges) UsersOrErr() (*Users, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "Users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatMessages) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatmessages.FieldID, chatmessages.FieldChatGroupID, chatmessages.FieldUserID:
			values[i] = new(sql.NullInt64)
		case chatmessages.FieldMessageText:
			values[i] = new(sql.NullString)
		case chatmessages.FieldDeletedAt, chatmessages.FieldCreatedAt, chatmessages.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatMessages fields.
func (_m *ChatMessages) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatmessages.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatmessages.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case chatmessages.FieldChatGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field chat_group_id", values[i])
			} else if value.Valid {
				_m.ChatGroupID = int(value.Int64)
			}
		case chatmessages.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case chatmessages.FieldMessageText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message_text", values[i])
			} else if value.Valid {
				_m.MessageText = value.String
			}
		case chatmessages.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatmessages.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatMessages.
// This includes values selected through modifiers, order, etc.
func (_m *ChatMessages) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryChatGroups queries the "ChatGroups" edge of the ChatMessages entity.
func (_m *ChatMessages) QueryChatGroups() *ChatGroupsQuery {
	return NewChatMessagesClient(_m.config).QueryChatGroups(_m)
}

// QueryUsers queries the "Users" edge of the ChatMessages entity.
func (_m *ChatMessages) QueryUsers() *UsersQuery {
	return NewChatMessagesClient(_m.config).QueryUsers(_m)
}

// Update returns a builder for updating this ChatMessages.
// Note that you need to call ChatMessages.Unwrap() before calling this method if this ChatMessages
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatMessages) Update() *ChatMessagesUpdateOne {
	return NewChatMessagesClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatMessages entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatMessages) Unwrap() *ChatMessages {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatMessages is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatMessages) String() string {
	var builder strings.Builder
	builder.WriteString("ChatMessages(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("chat_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ChatGroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("message_text=")
	builder.WriteString(_m.MessageText)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatMessagesSlice is a parsable slice of ChatMessages.
type ChatMessagesSlice []*ChatMessages
