// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-backend/ent/chatgroups"
	"go-backend/ent/users"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ChatGroups is the model entity for the ChatGroups schema.
type ChatGroups struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deletedAt"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"userId"`
	// Name holds the value of the "name" field.
	Name *string `json:"name"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ChatGroupsQuery when eager-loading is set.
	Edges        ChatGroupsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ChatGroupsEdges holds the relations/edges for other nodes in the graph.
type ChatGroupsEdges struct {
	// Users holds the value of the Users edge.
	Users *Users `json:"Users,omitempty"`
	// ChatGroupMembers holds the value of the ChatGroupMembers edge.
	ChatGroupMembers []*ChatGroupMembers `json:"ChatGroupMembers,omitempty"`
	// ChatMessages holds the value of the ChatMessages edge.
	ChatMessages []*ChatMessages `json:"ChatMessages,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ChatGroupsEdges) UsersOrErr() (*Users, error) {
	if e.Users != nil {
		return e.Users, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: users.Label}
	}
	return nil, &NotLoadedError{edge: "Users"}
}

// ChatGroupMembersOrErr returns the ChatGroupMembers value or an error if the edge
// was not loaded in eager-loading.
func (e ChatGroupsEdges) ChatGroupMembersOrErr() ([]*ChatGroupMembers, error) {
	if e.loadedTypes[1] {
		return e.ChatGroupMembers, nil
	}
	return nil, &NotLoadedError{edge: "ChatGroupMembers"}
}

// ChatMessagesOrErr returns the ChatMessages value or an error if the edge
// was not loaded in eager-loading.
func (e ChatGroupsEdges) ChatMessagesOrErr() ([]*ChatMessages, error) {
	if e.loadedTypes[2] {
		return e.ChatMessages, nil
	}
	return nil, &NotLoadedError{edge: "ChatMessages"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChatGroups) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case chatgroups.FieldID, chatgroups.FieldUserID:
			values[i] = new(sql.NullInt64)
		case chatgroups.FieldName:
			values[i] = new(sql.NullString)
		case chatgroups.FieldDeletedAt, chatgroups.FieldCreatedAt, chatgroups.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChatGroups fields.
func (_m *ChatGroups) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case chatgroups.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case chatgroups.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case chatgroups.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case chatgroups.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case chatgroups.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case chatgroups.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChatGroups.
// This includes values selected through modifiers, order, etc.
func (_m *ChatGroups) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUsers queries the "Users" edge of the ChatGroups entity.
func (_m *ChatGroups) QueryUsers() *UsersQuery {
	return NewChatGroupsClient(_m.config).QueryUsers(_m)
}

// QueryChatGroupMembers queries the "ChatGroupMembers" edge of the ChatGroups entity.
func (_m *ChatGroups) QueryChatGroupMembers() *ChatGroupMembersQuery {
	return NewChatGroupsClient(_m.config).QueryChatGroupMembers(_m)
}

// QueryChatMessages queries the "ChatMessages" edge of the ChatGroups entity.
func (_m *ChatGroups) QueryChatMessages() *ChatMessagesQuery {
	return NewChatGroupsClient(_m.config).QueryChatMessages(_m)
}

// Update returns a builder for updating this ChatGroups.
// Note that you need to call ChatGroups.Unwrap() before calling this method if this ChatGroups
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChatGroups) Update() *ChatGroupsUpdateOne {
	return NewChatGroupsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChatGroups entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChatGroups) Unwrap() *ChatGroups {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChatGroups is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChatGroups) String() string {
	var builder strings.Builder
	builder.WriteString("ChatGroups(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChatGroupsSlice is a parsable slice of ChatGroups.
type ChatGroupsSlice []*ChatGroups
