// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/chatgroups"
	"go-backend/ent/chatmessages"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatMessagesUpdate is the builder for updating ChatMessages entities.
type ChatMessagesUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMessagesMutation
}

// Where appends a list predicates to the ChatMessagesUpdate builder.
func (_u *ChatMessagesUpdate) Where(ps ...predicate.ChatMessages) *ChatMessagesUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatMessagesUpdate) SetDeletedAt(v time.Time) *ChatMessagesUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatMessagesUpdate) SetNillableDeletedAt(v *time.Time) *ChatMessagesUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatMessagesUpdate) ClearDeletedAt() *ChatMessagesUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChatGroupID sets the "chat_group_id" field.
func (_u *ChatMessagesUpdate) SetChatGroupID(v int) *ChatMessagesUpdate {
	_u.mutation.SetChatGroupID(v)
	return _u
}

// SetNillableChatGroupID sets the "chat_group_id" field if the given value is not nil.
func (_u *ChatMessagesUpdate) SetNillableChatGroupID(v *int) *ChatMessagesUpdate {
	if v != nil {
		_u.SetChatGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessagesUpdate) SetUserID(v int) *ChatMessagesUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessagesUpdate) SetNillableUserID(v *int) *ChatMessagesUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMessageText sets the "message_text" field.
func (_u *ChatMessagesUpdate) SetMessageText(v string) *ChatMessagesUpdate {
	_u.mutation.SetMessageText(v)
	return _u
}

// SetNillableMessageText sets the "message_text" field if the given value is not nil.
func (_u *ChatMessagesUpdate) SetNillableMessageText(v *string) *ChatMessagesUpdate {
	if v != nil {
		_u.SetMessageText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessagesUpdate) SetUpdatedAt(v time.Time) *ChatMessagesUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatGroupsID sets the "ChatGroups" edge to the ChatGroups entity by ID.
func (_u *ChatMessagesUpdate) SetChatGroupsID(id int) *ChatMessagesUpdate {
	_u.mutation.SetChatGroupsID(id)
	return _u
}

// SetChatGroups sets the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatMessagesUpdate) SetChatGroups(v *ChatGroups) *ChatMessagesUpdate {
	return _u.SetChatGroupsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatMessagesUpdate) SetUsersID(id int) *ChatMessagesUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatMessagesUpdate) SetUsers(v *Users) *ChatMessagesUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ChatMessagesMutation object of the builder.
func (_u *ChatMessagesUpdate) Mutation() *ChatMessagesMutation {
	return _u.mutation
}

// ClearChatGroups clears the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatMessagesUpdate) ClearChatGroups() *ChatMessagesUpdate {
	_u.mutation.ClearChatGroups()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatMessagesUpdate) ClearUsers() *ChatMessagesUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatMessagesUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessagesUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatMessagesUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessagesUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessagesUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatmessages.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatmessages.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatmessages.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessagesUpdate) check() error {
	if _u.mutation.ChatGroupsCleared() && len(_u.mutation.ChatGroupsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessages.ChatGroups"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessages.Users"`)
	}
	return nil
}

func (_u *ChatMessagesUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessages.Table, chatmessages.Columns, sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatmessages.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatmessages.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageText(); ok {
		_spec.SetField(chatmessages.FieldMessageText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessages.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.ChatGroupsTable,
			Columns: []string{chatmessages.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.ChatGroupsTable,
			Columns: []string{chatmessages.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.UsersTable,
			Columns: []string{chatmessages.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.UsersTable,
			Columns: []string{chatmessages.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessages.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatMessagesUpdateOne is the builder for updating a single ChatMessages entity.
type ChatMessagesUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMessagesMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatMessagesUpdateOne) SetDeletedAt(v time.Time) *ChatMessagesUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatMessagesUpdateOne) SetNillableDeletedAt(v *time.Time) *ChatMessagesUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatMessagesUpdateOne) ClearDeletedAt() *ChatMessagesUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChatGroupID sets the "chat_group_id" field.
func (_u *ChatMessagesUpdateOne) SetChatGroupID(v int) *ChatMessagesUpdateOne {
	_u.mutation.SetChatGroupID(v)
	return _u
}

// SetNillableChatGroupID sets the "chat_group_id" field if the given value is not nil.
func (_u *ChatMessagesUpdateOne) SetNillableChatGroupID(v *int) *ChatMessagesUpdateOne {
	if v != nil {
		_u.SetChatGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatMessagesUpdateOne) SetUserID(v int) *ChatMessagesUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatMessagesUpdateOne) SetNillableUserID(v *int) *ChatMessagesUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetMessageText sets the "message_text" field.
func (_u *ChatMessagesUpdateOne) SetMessageText(v string) *ChatMessagesUpdateOne {
	_u.mutation.SetMessageText(v)
	return _u
}

// SetNillableMessageText sets the "message_text" field if the given value is not nil.
func (_u *ChatMessagesUpdateOne) SetNillableMessageText(v *string) *ChatMessagesUpdateOne {
	if v != nil {
		_u.SetMessageText(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatMessagesUpdateOne) SetUpdatedAt(v time.Time) *ChatMessagesUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatGroupsID sets the "ChatGroups" edge to the ChatGroups entity by ID.
func (_u *ChatMessagesUpdateOne) SetChatGroupsID(id int) *ChatMessagesUpdateOne {
	_u.mutation.SetChatGroupsID(id)
	return _u
}

// SetChatGroups sets the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatMessagesUpdateOne) SetChatGroups(v *ChatGroups) *ChatMessagesUpdateOne {
	return _u.SetChatGroupsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatMessagesUpdateOne) SetUsersID(id int) *ChatMessagesUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatMessagesUpdateOne) SetUsers(v *Users) *ChatMessagesUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ChatMessagesMutation object of the builder.
func (_u *ChatMessagesUpdateOne) Mutation() *ChatMessagesMutation {
	return _u.mutation
}

// ClearChatGroups clears the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatMessagesUpdateOne) ClearChatGroups() *ChatMessagesUpdateOne {
	_u.mutation.ClearChatGroups()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatMessagesUpdateOne) ClearUsers() *ChatMessagesUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the ChatMessagesUpdate builder.
func (_u *ChatMessagesUpdateOne) Where(ps ...predicate.ChatMessages) *ChatMessagesUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatMessagesUpdateOne) Select(field string, fields ...string) *ChatMessagesUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatMessages entity.
func (_u *ChatMessagesUpdateOne) Save(ctx context.Context) (*ChatMessages, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatMessagesUpdateOne) SaveX(ctx context.Context) *ChatMessages {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatMessagesUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatMessagesUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatMessagesUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatmessages.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatmessages.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatmessages.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatMessagesUpdateOne) check() error {
	if _u.mutation.ChatGroupsCleared() && len(_u.mutation.ChatGroupsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessages.ChatGroups"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatMessages.Users"`)
	}
	return nil
}

func (_u *ChatMessagesUpdateOne) sqlSave(ctx context.Context) (_node *ChatMessages, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatmessages.Table, chatmessages.Columns, sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatMessages.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatmessages.FieldID)
		for _, f := range fields {
			if !chatmessages.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatmessages.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatmessages.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatmessages.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.MessageText(); ok {
		_spec.SetField(chatmessages.FieldMessageText, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatmessages.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.ChatGroupsTable,
			Columns: []string{chatmessages.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.ChatGroupsTable,
			Columns: []string{chatmessages.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.UsersTable,
			Columns: []string{chatmessages.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatmessages.UsersTable,
			Columns: []string{chatmessages.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatMessages{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatmessages.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
