// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/chatmessages"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupsUpdate is the builder for updating ChatGroups entities.
type ChatGroupsUpdate struct {
	config
	hooks    []Hook
	mutation *ChatGroupsMutation
}

// Where appends a list predicates to the ChatGroupsUpdate builder.
func (_u *ChatGroupsUpdate) Where(ps ...predicate.ChatGroups) *ChatGroupsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatGroupsUpdate) SetDeletedAt(v time.Time) *ChatGroupsUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatGroupsUpdate) SetNillableDeletedAt(v *time.Time) *ChatGroupsUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatGroupsUpdate) ClearDeletedAt() *ChatGroupsUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatGroupsUpdate) SetUserID(v int) *ChatGroupsUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatGroupsUpdate) SetNillableUserID(v *int) *ChatGroupsUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChatGroupsUpdate) SetName(v string) *ChatGroupsUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatGroupsUpdate) SetNillableName(v *string) *ChatGroupsUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChatGroupsUpdate) ClearName() *ChatGroupsUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatGroupsUpdate) SetUpdatedAt(v time.Time) *ChatGroupsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatGroupsUpdate) SetUsersID(id int) *ChatGroupsUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatGroupsUpdate) SetUsers(v *Users) *ChatGroupsUpdate {
	return _u.SetUsersID(v.ID)
}

// AddChatGroupMemberIDs adds the "ChatGroupMembers" edge to the ChatGroupMembers entity by IDs.
func (_u *ChatGroupsUpdate) AddChatGroupMemberIDs(ids ...int) *ChatGroupsUpdate {
	_u.mutation.AddChatGroupMemberIDs(ids...)
	return _u
}

// AddChatGroupMembers adds the "ChatGroupMembers" edges to the ChatGroupMembers entity.
func (_u *ChatGroupsUpdate) AddChatGroupMembers(v ...*ChatGroupMembers) *ChatGroupsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatGroupMemberIDs(ids...)
}

// AddChatMessageIDs adds the "ChatMessages" edge to the ChatMessages entity by IDs.
func (_u *ChatGroupsUpdate) AddChatMessageIDs(ids ...int) *ChatGroupsUpdate {
	_u.mutation.AddChatMessageIDs(ids...)
	return _u
}

// AddChatMessages adds the "ChatMessages" edges to the ChatMessages entity.
func (_u *ChatGroupsUpdate) AddChatMessages(v ...*ChatMessages) *ChatGroupsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatMessageIDs(ids...)
}

// Mutation returns the ChatGroupsMutation object of the builder.
func (_u *ChatGroupsUpdate) Mutation() *ChatGroupsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatGroupsUpdate) ClearUsers() *ChatGroupsUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// ClearChatGroupMembers clears all "ChatGroupMembers" edges to the ChatGroupMembers entity.
func (_u *ChatGroupsUpdate) ClearChatGroupMembers() *ChatGroupsUpdate {
	_u.mutation.ClearChatGroupMembers()
	return _u
}

// RemoveChatGroupMemberIDs removes the "ChatGroupMembers" edge to ChatGroupMembers entities by IDs.
func (_u *ChatGroupsUpdate) RemoveChatGroupMemberIDs(ids ...int) *ChatGroupsUpdate {
	_u.mutation.RemoveChatGroupMemberIDs(ids...)
	return _u
}

// RemoveChatGroupMembers removes "ChatGroupMembers" edges to ChatGroupMembers entities.
func (_u *ChatGroupsUpdate) RemoveChatGroupMembers(v ...*ChatGroupMembers) *ChatGroupsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatGroupMemberIDs(ids...)
}

// ClearChatMessages clears all "ChatMessages" edges to the ChatMessages entity.
func (_u *ChatGroupsUpdate) ClearChatMessages() *ChatGroupsUpdate {
	_u.mutation.ClearChatMessages()
	return _u
}

// RemoveChatMessageIDs removes the "ChatMessages" edge to ChatMessages entities by IDs.
func (_u *ChatGroupsUpdate) RemoveChatMessageIDs(ids ...int) *ChatGroupsUpdate {
	_u.mutation.RemoveChatMessageIDs(ids...)
	return _u
}

// RemoveChatMessages removes "ChatMessages" edges to ChatMessages entities.
func (_u *ChatGroupsUpdate) RemoveChatMessages(v ...*ChatMessages) *ChatGroupsUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatGroupsUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatGroupsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatGroupsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatGroupsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatGroupsUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatgroups.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroups.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroups.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatGroupsUpdate) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroups.Users"`)
	}
	return nil
}

func (_u *ChatGroupsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatgroups.Table, chatgroups.Columns, sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroups.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatgroups.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatgroups.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(chatgroups.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroups.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroups.UsersTable,
			Columns: []string{chatgroups.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroups.UsersTable,
			Columns: []string{chatgroups.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatGroupMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatGroupMembersIDs(); len(nodes) > 0 && !_u.mutation.ChatGroupMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatMessagesIDs(); len(nodes) > 0 && !_u.mutation.ChatMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatgroups.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatGroupsUpdateOne is the builder for updating a single ChatGroups entity.
type ChatGroupsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatGroupsMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatGroupsUpdateOne) SetDeletedAt(v time.Time) *ChatGroupsUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatGroupsUpdateOne) SetNillableDeletedAt(v *time.Time) *ChatGroupsUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatGroupsUpdateOne) ClearDeletedAt() *ChatGroupsUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatGroupsUpdateOne) SetUserID(v int) *ChatGroupsUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatGroupsUpdateOne) SetNillableUserID(v *int) *ChatGroupsUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ChatGroupsUpdateOne) SetName(v string) *ChatGroupsUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ChatGroupsUpdateOne) SetNillableName(v *string) *ChatGroupsUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *ChatGroupsUpdateOne) ClearName() *ChatGroupsUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatGroupsUpdateOne) SetUpdatedAt(v time.Time) *ChatGroupsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatGroupsUpdateOne) SetUsersID(id int) *ChatGroupsUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatGroupsUpdateOne) SetUsers(v *Users) *ChatGroupsUpdateOne {
	return _u.SetUsersID(v.ID)
}

// AddChatGroupMemberIDs adds the "ChatGroupMembers" edge to the ChatGroupMembers entity by IDs.
func (_u *ChatGroupsUpdateOne) AddChatGroupMemberIDs(ids ...int) *ChatGroupsUpdateOne {
	_u.mutation.AddChatGroupMemberIDs(ids...)
	return _u
}

// AddChatGroupMembers adds the "ChatGroupMembers" edges to the ChatGroupMembers entity.
func (_u *ChatGroupsUpdateOne) AddChatGroupMembers(v ...*ChatGroupMembers) *ChatGroupsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatGroupMemberIDs(ids...)
}

// AddChatMessageIDs adds the "ChatMessages" edge to the ChatMessages entity by IDs.
func (_u *ChatGroupsUpdateOne) AddChatMessageIDs(ids ...int) *ChatGroupsUpdateOne {
	_u.mutation.AddChatMessageIDs(ids...)
	return _u
}

// AddChatMessages adds the "ChatMessages" edges to the ChatMessages entity.
func (_u *ChatGroupsUpdateOne) AddChatMessages(v ...*ChatMessages) *ChatGroupsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddChatMessageIDs(ids...)
}

// Mutation returns the ChatGroupsMutation object of the builder.
func (_u *ChatGroupsUpdateOne) Mutation() *ChatGroupsMutation {
	return _u.mutation
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatGroupsUpdateOne) ClearUsers() *ChatGroupsUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// ClearChatGroupMembers clears all "ChatGroupMembers" edges to the ChatGroupMembers entity.
func (_u *ChatGroupsUpdateOne) ClearChatGroupMembers() *ChatGroupsUpdateOne {
	_u.mutation.ClearChatGroupMembers()
	return _u
}

// RemoveChatGroupMemberIDs removes the "ChatGroupMembers" edge to ChatGroupMembers entities by IDs.
func (_u *ChatGroupsUpdateOne) RemoveChatGroupMemberIDs(ids ...int) *ChatGroupsUpdateOne {
	_u.mutation.RemoveChatGroupMemberIDs(ids...)
	return _u
}

// RemoveChatGroupMembers removes "ChatGroupMembers" edges to ChatGroupMembers entities.
func (_u *ChatGroupsUpdateOne) RemoveChatGroupMembers(v ...*ChatGroupMembers) *ChatGroupsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatGroupMemberIDs(ids...)
}

// ClearChatMessages clears all "ChatMessages" edges to the ChatMessages entity.
func (_u *ChatGroupsUpdateOne) ClearChatMessages() *ChatGroupsUpdateOne {
	_u.mutation.ClearChatMessages()
	return _u
}

// RemoveChatMessageIDs removes the "ChatMessages" edge to ChatMessages entities by IDs.
func (_u *ChatGroupsUpdateOne) RemoveChatMessageIDs(ids ...int) *ChatGroupsUpdateOne {
	_u.mutation.RemoveChatMessageIDs(ids...)
	return _u
}

// RemoveChatMessages removes "ChatMessages" edges to ChatMessages entities.
func (_u *ChatGroupsUpdateOne) RemoveChatMessages(v ...*ChatMessages) *ChatGroupsUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveChatMessageIDs(ids...)
}

// Where appends a list predicates to the ChatGroupsUpdate builder.
func (_u *ChatGroupsUpdateOne) Where(ps ...predicate.ChatGroups) *ChatGroupsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatGroupsUpdateOne) Select(field string, fields ...string) *ChatGroupsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatGroups entity.
func (_u *ChatGroupsUpdateOne) Save(ctx context.Context) (*ChatGroups, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatGroupsUpdateOne) SaveX(ctx context.Context) *ChatGroups {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatGroupsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatGroupsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatGroupsUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatgroups.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroups.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroups.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatGroupsUpdateOne) check() error {
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroups.Users"`)
	}
	return nil
}

func (_u *ChatGroupsUpdateOne) sqlSave(ctx context.Context) (_node *ChatGroups, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatgroups.Table, chatgroups.Columns, sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatGroups.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatgroups.FieldID)
		for _, f := range fields {
			if !chatgroups.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatgroups.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroups.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatgroups.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(chatgroups.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(chatgroups.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroups.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroups.UsersTable,
			Columns: []string{chatgroups.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroups.UsersTable,
			Columns: []string{chatgroups.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatGroupMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatGroupMembersIDs(); len(nodes) > 0 && !_u.mutation.ChatGroupMembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ChatMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedChatMessagesIDs(); len(nodes) > 0 && !_u.mutation.ChatMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatGroups{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatgroups.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
