// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupMembersQuery is the builder for querying ChatGroupMembers entities.
type ChatGroupMembersQuery struct {
	config
	ctx            *QueryContext
	order          []chatgroupmembers.OrderOption
	inters         []Interceptor
	predicates     []predicate.ChatGroupMembers
	withChatGroups *ChatGroupsQuery
	withUsers      *UsersQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatGroupMembersQuery builder.
func (_q *ChatGroupMembersQuery) Where(ps ...predicate.ChatGroupMembers) *ChatGroupMembersQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatGroupMembersQuery) Limit(limit int) *ChatGroupMembersQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatGroupMembersQuery) Offset(offset int) *ChatGroupMembersQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatGroupMembersQuery) Unique(unique bool) *ChatGroupMembersQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatGroupMembersQuery) Order(o ...chatgroupmembers.OrderOption) *ChatGroupMembersQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryChatGroups chains the current query on the "ChatGroups" edge.
func (_q *ChatGroupMembersQuery) QueryChatGroups() *ChatGroupsQuery {
	query := (&ChatGroupsClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatgroupmembers.Table, chatgroupmembers.FieldID, selector),
			sqlgraph.To(chatgroups.Table, chatgroups.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatgroupmembers.ChatGroupsTable, chatgroupmembers.ChatGroupsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUsers chains the current query on the "Users" edge.
func (_q *ChatGroupMembersQuery) QueryUsers() *UsersQuery {
	query := (&UsersClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatgroupmembers.Table, chatgroupmembers.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatgroupmembers.UsersTable, chatgroupmembers.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatGroupMembers entity from the query.
// Returns a *NotFoundError when no ChatGroupMembers was found.
func (_q *ChatGroupMembersQuery) First(ctx context.Context) (*ChatGroupMembers, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatgroupmembers.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) FirstX(ctx context.Context) *ChatGroupMembers {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatGroupMembers ID from the query.
// Returns a *NotFoundError when no ChatGroupMembers ID was found.
func (_q *ChatGroupMembersQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatgroupmembers.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatGroupMembers entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatGroupMembers entity is found.
// Returns a *NotFoundError when no ChatGroupMembers entities are found.
func (_q *ChatGroupMembersQuery) Only(ctx context.Context) (*ChatGroupMembers, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatgroupmembers.Label}
	default:
		return nil, &NotSingularError{chatgroupmembers.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) OnlyX(ctx context.Context) *ChatGroupMembers {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatGroupMembers ID in the query.
// Returns a *NotSingularError when more than one ChatGroupMembers ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatGroupMembersQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatgroupmembers.Label}
	default:
		err = &NotSingularError{chatgroupmembers.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatGroupMembersSlice.
func (_q *ChatGroupMembersQuery) All(ctx context.Context) ([]*ChatGroupMembers, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatGroupMembers, *ChatGroupMembersQuery]()
	return withInterceptors[[]*ChatGroupMembers](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) AllX(ctx context.Context) []*ChatGroupMembers {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatGroupMembers IDs.
func (_q *ChatGroupMembersQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatgroupmembers.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatGroupMembersQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatGroupMembersQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatGroupMembersQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatGroupMembersQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatGroupMembersQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatGroupMembersQuery) Clone() *ChatGroupMembersQuery {
	if _q == nil {
		return nil
	}
	return &ChatGroupMembersQuery{
		config:         _q.config,
		ctx:            _q.ctx.Clone(),
		order:          append([]chatgroupmembers.OrderOption{}, _q.order...),
		inters:         append([]Interceptor{}, _q.inters...),
		predicates:     append([]predicate.ChatGroupMembers{}, _q.predicates...),
		withChatGroups: _q.withChatGroups.Clone(),
		withUsers:      _q.withUsers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithChatGroups tells the query-builder to eager-load the nodes that are connected to
// the "ChatGroups" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatGroupMembersQuery) WithChatGroups(opts ...func(*ChatGroupsQuery)) *ChatGroupMembersQuery {
	query := (&ChatGroupsClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChatGroups = query
	return _q
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "Users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatGroupMembersQuery) WithUsers(opts ...func(*UsersQuery)) *ChatGroupMembersQuery {
	query := (&UsersClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deletedAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatGroupMembers.Query().
//		GroupBy(chatgroupmembers.FieldDeletedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatGroupMembersQuery) GroupBy(field string, fields ...string) *ChatGroupMembersGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatGroupMembersGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatgroupmembers.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deletedAt"`
//	}
//
//	client.ChatGroupMembers.Query().
//		Select(chatgroupmembers.FieldDeletedAt).
//		Scan(ctx, &v)
func (_q *ChatGroupMembersQuery) Select(fields ...string) *ChatGroupMembersSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatGroupMembersSelect{ChatGroupMembersQuery: _q}
	sbuild.label = chatgroupmembers.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatGroupMembersSelect configured with the given aggregations.
func (_q *ChatGroupMembersQuery) Aggregate(fns ...AggregateFunc) *ChatGroupMembersSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatGroupMembersQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatgroupmembers.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatGroupMembersQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatGroupMembers, error) {
	var (
		nodes       = []*ChatGroupMembers{}
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withChatGroups != nil,
			_q.withUsers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatGroupMembers).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatGroupMembers{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withChatGroups; query != nil {
		if err := _q.loadChatGroups(ctx, query, nodes, nil,
			func(n *ChatGroupMembers, e *ChatGroups) { n.Edges.ChatGroups = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withUsers; query != nil {
		if err := _q.loadUsers(ctx, query, nodes, nil,
			func(n *ChatGroupMembers, e *Users) { n.Edges.Users = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatGroupMembersQuery) loadChatGroups(ctx context.Context, query *ChatGroupsQuery, nodes []*ChatGroupMembers, init func(*ChatGroupMembers), assign func(*ChatGroupMembers, *ChatGroups)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatGroupMembers)
	for i := range nodes {
		fk := nodes[i].ChatGroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(chatgroups.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "chat_group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChatGroupMembersQuery) loadUsers(ctx context.Context, query *UsersQuery, nodes []*ChatGroupMembers, init func(*ChatGroupMembers), assign func(*ChatGroupMembers, *Users)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatGroupMembers)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *ChatGroupMembersQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatGroupMembersQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatgroupmembers.Table, chatgroupmembers.Columns, sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatgroupmembers.FieldID)
		for i := range fields {
			if fields[i] != chatgroupmembers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withChatGroups != nil {
			_spec.Node.AddColumnOnce(chatgroupmembers.FieldChatGroupID)
		}
		if _q.withUsers != nil {
			_spec.Node.AddColumnOnce(chatgroupmembers.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatGroupMembersQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatgroupmembers.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatgroupmembers.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatGroupMembersGroupBy is the group-by builder for ChatGroupMembers entities.
type ChatGroupMembersGroupBy struct {
	selector
	build *ChatGroupMembersQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatGroupMembersGroupBy) Aggregate(fns ...AggregateFunc) *ChatGroupMembersGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatGroupMembersGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatGroupMembersQuery, *ChatGroupMembersGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatGroupMembersGroupBy) sqlScan(ctx context.Context, root *ChatGroupMembersQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatGroupMembersSelect is the builder for selecting fields of ChatGroupMembers entities.
type ChatGroupMembersSelect struct {
	*ChatGroupMembersQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatGroupMembersSelect) Aggregate(fns ...AggregateFunc) *ChatGroupMembersSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatGroupMembersSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatGroupMembersQuery, *ChatGroupMembersSelect](ctx, _s.ChatGroupMembersQuery, _s, _s.inters, v)
}

func (_s *ChatGroupMembersSelect) sqlScan(ctx context.Context, root *ChatGroupMembersQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
