// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupMembersUpdate is the builder for updating ChatGroupMembers entities.
type ChatGroupMembersUpdate struct {
	config
	hooks    []Hook
	mutation *ChatGroupMembersMutation
}

// Where appends a list predicates to the ChatGroupMembersUpdate builder.
func (_u *ChatGroupMembersUpdate) Where(ps ...predicate.ChatGroupMembers) *ChatGroupMembersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatGroupMembersUpdate) SetDeletedAt(v time.Time) *ChatGroupMembersUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatGroupMembersUpdate) SetNillableDeletedAt(v *time.Time) *ChatGroupMembersUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatGroupMembersUpdate) ClearDeletedAt() *ChatGroupMembersUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChatGroupID sets the "chat_group_id" field.
func (_u *ChatGroupMembersUpdate) SetChatGroupID(v int) *ChatGroupMembersUpdate {
	_u.mutation.SetChatGroupID(v)
	return _u
}

// SetNillableChatGroupID sets the "chat_group_id" field if the given value is not nil.
func (_u *ChatGroupMembersUpdate) SetNillableChatGroupID(v *int) *ChatGroupMembersUpdate {
	if v != nil {
		_u.SetChatGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatGroupMembersUpdate) SetUserID(v int) *ChatGroupMembersUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatGroupMembersUpdate) SetNillableUserID(v *int) *ChatGroupMembersUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatGroupMembersUpdate) SetUpdatedAt(v time.Time) *ChatGroupMembersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatGroupsID sets the "ChatGroups" edge to the ChatGroups entity by ID.
func (_u *ChatGroupMembersUpdate) SetChatGroupsID(id int) *ChatGroupMembersUpdate {
	_u.mutation.SetChatGroupsID(id)
	return _u
}

// SetChatGroups sets the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatGroupMembersUpdate) SetChatGroups(v *ChatGroups) *ChatGroupMembersUpdate {
	return _u.SetChatGroupsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatGroupMembersUpdate) SetUsersID(id int) *ChatGroupMembersUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatGroupMembersUpdate) SetUsers(v *Users) *ChatGroupMembersUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ChatGroupMembersMutation object of the builder.
func (_u *ChatGroupMembersUpdate) Mutation() *ChatGroupMembersMutation {
	return _u.mutation
}

// ClearChatGroups clears the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatGroupMembersUpdate) ClearChatGroups() *ChatGroupMembersUpdate {
	_u.mutation.ClearChatGroups()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatGroupMembersUpdate) ClearUsers() *ChatGroupMembersUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ChatGroupMembersUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatGroupMembersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ChatGroupMembersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatGroupMembersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatGroupMembersUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatgroupmembers.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroupmembers.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroupmembers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatGroupMembersUpdate) check() error {
	if _u.mutation.ChatGroupsCleared() && len(_u.mutation.ChatGroupsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroupMembers.ChatGroups"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroupMembers.Users"`)
	}
	return nil
}

func (_u *ChatGroupMembersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatgroupmembers.Table, chatgroupmembers.Columns, sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatgroupmembers.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.ChatGroupsTable,
			Columns: []string{chatgroupmembers.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.ChatGroupsTable,
			Columns: []string{chatgroupmembers.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.UsersTable,
			Columns: []string{chatgroupmembers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.UsersTable,
			Columns: []string{chatgroupmembers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatgroupmembers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ChatGroupMembersUpdateOne is the builder for updating a single ChatGroupMembers entity.
type ChatGroupMembersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatGroupMembersMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ChatGroupMembersUpdateOne) SetDeletedAt(v time.Time) *ChatGroupMembersUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ChatGroupMembersUpdateOne) SetNillableDeletedAt(v *time.Time) *ChatGroupMembersUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ChatGroupMembersUpdateOne) ClearDeletedAt() *ChatGroupMembersUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetChatGroupID sets the "chat_group_id" field.
func (_u *ChatGroupMembersUpdateOne) SetChatGroupID(v int) *ChatGroupMembersUpdateOne {
	_u.mutation.SetChatGroupID(v)
	return _u
}

// SetNillableChatGroupID sets the "chat_group_id" field if the given value is not nil.
func (_u *ChatGroupMembersUpdateOne) SetNillableChatGroupID(v *int) *ChatGroupMembersUpdateOne {
	if v != nil {
		_u.SetChatGroupID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ChatGroupMembersUpdateOne) SetUserID(v int) *ChatGroupMembersUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ChatGroupMembersUpdateOne) SetNillableUserID(v *int) *ChatGroupMembersUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ChatGroupMembersUpdateOne) SetUpdatedAt(v time.Time) *ChatGroupMembersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetChatGroupsID sets the "ChatGroups" edge to the ChatGroups entity by ID.
func (_u *ChatGroupMembersUpdateOne) SetChatGroupsID(id int) *ChatGroupMembersUpdateOne {
	_u.mutation.SetChatGroupsID(id)
	return _u
}

// SetChatGroups sets the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatGroupMembersUpdateOne) SetChatGroups(v *ChatGroups) *ChatGroupMembersUpdateOne {
	return _u.SetChatGroupsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *ChatGroupMembersUpdateOne) SetUsersID(id int) *ChatGroupMembersUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *ChatGroupMembersUpdateOne) SetUsers(v *Users) *ChatGroupMembersUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the ChatGroupMembersMutation object of the builder.
func (_u *ChatGroupMembersUpdateOne) Mutation() *ChatGroupMembersMutation {
	return _u.mutation
}

// ClearChatGroups clears the "ChatGroups" edge to the ChatGroups entity.
func (_u *ChatGroupMembersUpdateOne) ClearChatGroups() *ChatGroupMembersUpdateOne {
	_u.mutation.ClearChatGroups()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *ChatGroupMembersUpdateOne) ClearUsers() *ChatGroupMembersUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the ChatGroupMembersUpdate builder.
func (_u *ChatGroupMembersUpdateOne) Where(ps ...predicate.ChatGroupMembers) *ChatGroupMembersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ChatGroupMembersUpdateOne) Select(field string, fields ...string) *ChatGroupMembersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ChatGroupMembers entity.
func (_u *ChatGroupMembersUpdateOne) Save(ctx context.Context) (*ChatGroupMembers, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ChatGroupMembersUpdateOne) SaveX(ctx context.Context) *ChatGroupMembers {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ChatGroupMembersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ChatGroupMembersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ChatGroupMembersUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if chatgroupmembers.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroupmembers.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroupmembers.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ChatGroupMembersUpdateOne) check() error {
	if _u.mutation.ChatGroupsCleared() && len(_u.mutation.ChatGroupsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroupMembers.ChatGroups"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ChatGroupMembers.Users"`)
	}
	return nil
}

func (_u *ChatGroupMembersUpdateOne) sqlSave(ctx context.Context) (_node *ChatGroupMembers, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chatgroupmembers.Table, chatgroupmembers.Columns, sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ChatGroupMembers.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatgroupmembers.FieldID)
		for _, f := range fields {
			if !chatgroupmembers.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chatgroupmembers.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(chatgroupmembers.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ChatGroupsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.ChatGroupsTable,
			Columns: []string{chatgroupmembers.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ChatGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.ChatGroupsTable,
			Columns: []string{chatgroupmembers.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.UsersTable,
			Columns: []string{chatgroupmembers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.UsersTable,
			Columns: []string{chatgroupmembers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ChatGroupMembers{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chatgroupmembers.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
