// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/chatmessages"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupsCreate is the builder for creating a ChatGroups entity.
type ChatGroupsCreate struct {
	config
	mutation *ChatGroupsMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChatGroupsCreate) SetDeletedAt(v time.Time) *ChatGroupsCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChatGroupsCreate) SetNillableDeletedAt(v *time.Time) *ChatGroupsCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatGroupsCreate) SetUserID(v int) *ChatGroupsCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ChatGroupsCreate) SetName(v string) *ChatGroupsCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *ChatGroupsCreate) SetNillableName(v *string) *ChatGroupsCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatGroupsCreate) SetCreatedAt(v time.Time) *ChatGroupsCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatGroupsCreate) SetNillableCreatedAt(v *time.Time) *ChatGroupsCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatGroupsCreate) SetUpdatedAt(v time.Time) *ChatGroupsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatGroupsCreate) SetNillableUpdatedAt(v *time.Time) *ChatGroupsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_c *ChatGroupsCreate) SetUsersID(id int) *ChatGroupsCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "Users" edge to the Users entity.
func (_c *ChatGroupsCreate) SetUsers(v *Users) *ChatGroupsCreate {
	return _c.SetUsersID(v.ID)
}

// AddChatGroupMemberIDs adds the "ChatGroupMembers" edge to the ChatGroupMembers entity by IDs.
func (_c *ChatGroupsCreate) AddChatGroupMemberIDs(ids ...int) *ChatGroupsCreate {
	_c.mutation.AddChatGroupMemberIDs(ids...)
	return _c
}

// AddChatGroupMembers adds the "ChatGroupMembers" edges to the ChatGroupMembers entity.
func (_c *ChatGroupsCreate) AddChatGroupMembers(v ...*ChatGroupMembers) *ChatGroupsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatGroupMemberIDs(ids...)
}

// AddChatMessageIDs adds the "ChatMessages" edge to the ChatMessages entity by IDs.
func (_c *ChatGroupsCreate) AddChatMessageIDs(ids ...int) *ChatGroupsCreate {
	_c.mutation.AddChatMessageIDs(ids...)
	return _c
}

// AddChatMessages adds the "ChatMessages" edges to the ChatMessages entity.
func (_c *ChatGroupsCreate) AddChatMessages(v ...*ChatMessages) *ChatGroupsCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddChatMessageIDs(ids...)
}

// Mutation returns the ChatGroupsMutation object of the builder.
func (_c *ChatGroupsCreate) Mutation() *ChatGroupsMutation {
	return _c.mutation
}

// Save creates the ChatGroups in the database.
func (_c *ChatGroupsCreate) Save(ctx context.Context) (*ChatGroups, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatGroupsCreate) SaveX(ctx context.Context) *ChatGroups {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatGroupsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatGroupsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatGroupsCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if chatgroups.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroups.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroups.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if chatgroups.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroups.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroups.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatGroupsCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatGroups.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatGroups.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatGroups.updated_at"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "Users", err: errors.New(`ent: missing required edge "ChatGroups.Users"`)}
	}
	return nil
}

func (_c *ChatGroupsCreate) sqlSave(ctx context.Context) (*ChatGroups, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatGroupsCreate) createSpec() (*ChatGroups, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatGroups{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatgroups.Table, sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroups.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(chatgroups.FieldName, field.TypeString, value)
		_node.Name = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatgroups.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroups.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroups.UsersTable,
			Columns: []string{chatgroups.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatGroupMembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatGroupMembersTable,
			Columns: []string{chatgroups.ChatGroupMembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ChatMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chatgroups.ChatMessagesTable,
			Columns: []string{chatgroups.ChatMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatmessages.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatGroupsCreateBulk is the builder for creating many ChatGroups entities in bulk.
type ChatGroupsCreateBulk struct {
	config
	err      error
	builders []*ChatGroupsCreate
}

// Save creates the ChatGroups entities in the database.
func (_c *ChatGroupsCreateBulk) Save(ctx context.Context) ([]*ChatGroups, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatGroups, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatGroupsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatGroupsCreateBulk) SaveX(ctx context.Context) []*ChatGroups {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatGroupsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatGroupsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
