// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupMembersCreate is the builder for creating a ChatGroupMembers entity.
type ChatGroupMembersCreate struct {
	config
	mutation *ChatGroupMembersMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *ChatGroupMembersCreate) SetDeletedAt(v time.Time) *ChatGroupMembersCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *ChatGroupMembersCreate) SetNillableDeletedAt(v *time.Time) *ChatGroupMembersCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetChatGroupID sets the "chat_group_id" field.
func (_c *ChatGroupMembersCreate) SetChatGroupID(v int) *ChatGroupMembersCreate {
	_c.mutation.SetChatGroupID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ChatGroupMembersCreate) SetUserID(v int) *ChatGroupMembersCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ChatGroupMembersCreate) SetCreatedAt(v time.Time) *ChatGroupMembersCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ChatGroupMembersCreate) SetNillableCreatedAt(v *time.Time) *ChatGroupMembersCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ChatGroupMembersCreate) SetUpdatedAt(v time.Time) *ChatGroupMembersCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ChatGroupMembersCreate) SetNillableUpdatedAt(v *time.Time) *ChatGroupMembersCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetChatGroupsID sets the "ChatGroups" edge to the ChatGroups entity by ID.
func (_c *ChatGroupMembersCreate) SetChatGroupsID(id int) *ChatGroupMembersCreate {
	_c.mutation.SetChatGroupsID(id)
	return _c
}

// SetChatGroups sets the "ChatGroups" edge to the ChatGroups entity.
func (_c *ChatGroupMembersCreate) SetChatGroups(v *ChatGroups) *ChatGroupMembersCreate {
	return _c.SetChatGroupsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_c *ChatGroupMembersCreate) SetUsersID(id int) *ChatGroupMembersCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "Users" edge to the Users entity.
func (_c *ChatGroupMembersCreate) SetUsers(v *Users) *ChatGroupMembersCreate {
	return _c.SetUsersID(v.ID)
}

// Mutation returns the ChatGroupMembersMutation object of the builder.
func (_c *ChatGroupMembersCreate) Mutation() *ChatGroupMembersMutation {
	return _c.mutation
}

// Save creates the ChatGroupMembers in the database.
func (_c *ChatGroupMembersCreate) Save(ctx context.Context) (*ChatGroupMembers, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ChatGroupMembersCreate) SaveX(ctx context.Context) *ChatGroupMembers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatGroupMembersCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatGroupMembersCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ChatGroupMembersCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if chatgroupmembers.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroupmembers.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroupmembers.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if chatgroupmembers.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized chatgroupmembers.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := chatgroupmembers.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *ChatGroupMembersCreate) check() error {
	if _, ok := _c.mutation.ChatGroupID(); !ok {
		return &ValidationError{Name: "chat_group_id", err: errors.New(`ent: missing required field "ChatGroupMembers.chat_group_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ChatGroupMembers.user_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChatGroupMembers.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChatGroupMembers.updated_at"`)}
	}
	if len(_c.mutation.ChatGroupsIDs()) == 0 {
		return &ValidationError{Name: "ChatGroups", err: errors.New(`ent: missing required edge "ChatGroupMembers.ChatGroups"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "Users", err: errors.New(`ent: missing required edge "ChatGroupMembers.Users"`)}
	}
	return nil
}

func (_c *ChatGroupMembersCreate) sqlSave(ctx context.Context) (*ChatGroupMembers, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ChatGroupMembersCreate) createSpec() (*ChatGroupMembers, *sqlgraph.CreateSpec) {
	var (
		_node = &ChatGroupMembers{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(chatgroupmembers.Table, sqlgraph.NewFieldSpec(chatgroupmembers.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(chatgroupmembers.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.ChatGroupsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.ChatGroupsTable,
			Columns: []string{chatgroupmembers.ChatGroupsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ChatGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chatgroupmembers.UsersTable,
			Columns: []string{chatgroupmembers.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatGroupMembersCreateBulk is the builder for creating many ChatGroupMembers entities in bulk.
type ChatGroupMembersCreateBulk struct {
	config
	err      error
	builders []*ChatGroupMembersCreate
}

// Save creates the ChatGroupMembers entities in the database.
func (_c *ChatGroupMembersCreateBulk) Save(ctx context.Context) ([]*ChatGroupMembers, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ChatGroupMembers, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatGroupMembersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ChatGroupMembersCreateBulk) SaveX(ctx context.Context) []*ChatGroupMembers {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ChatGroupMembersCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ChatGroupMembersCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
