// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"go-backend/ent/chatgroupmembers"
	"go-backend/ent/chatgroups"
	"go-backend/ent/chatmessages"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ChatGroupsQuery is the builder for querying ChatGroups entities.
type ChatGroupsQuery struct {
	config
	ctx                  *QueryContext
	order                []chatgroups.OrderOption
	inters               []Interceptor
	predicates           []predicate.ChatGroups
	withUsers            *UsersQuery
	withChatGroupMembers *ChatGroupMembersQuery
	withChatMessages     *ChatMessagesQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatGroupsQuery builder.
func (_q *ChatGroupsQuery) Where(ps ...predicate.ChatGroups) *ChatGroupsQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *ChatGroupsQuery) Limit(limit int) *ChatGroupsQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *ChatGroupsQuery) Offset(offset int) *ChatGroupsQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *ChatGroupsQuery) Unique(unique bool) *ChatGroupsQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *ChatGroupsQuery) Order(o ...chatgroups.OrderOption) *ChatGroupsQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUsers chains the current query on the "Users" edge.
func (_q *ChatGroupsQuery) QueryUsers() *UsersQuery {
	query := (&UsersClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatgroups.Table, chatgroups.FieldID, selector),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, chatgroups.UsersTable, chatgroups.UsersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChatGroupMembers chains the current query on the "ChatGroupMembers" edge.
func (_q *ChatGroupsQuery) QueryChatGroupMembers() *ChatGroupMembersQuery {
	query := (&ChatGroupMembersClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatgroups.Table, chatgroups.FieldID, selector),
			sqlgraph.To(chatgroupmembers.Table, chatgroupmembers.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, chatgroups.ChatGroupMembersTable, chatgroups.ChatGroupMembersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChatMessages chains the current query on the "ChatMessages" edge.
func (_q *ChatGroupsQuery) QueryChatMessages() *ChatMessagesQuery {
	query := (&ChatMessagesClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(chatgroups.Table, chatgroups.FieldID, selector),
			sqlgraph.To(chatmessages.Table, chatmessages.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, chatgroups.ChatMessagesTable, chatgroups.ChatMessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ChatGroups entity from the query.
// Returns a *NotFoundError when no ChatGroups was found.
func (_q *ChatGroupsQuery) First(ctx context.Context) (*ChatGroups, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatgroups.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *ChatGroupsQuery) FirstX(ctx context.Context) *ChatGroups {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatGroups ID from the query.
// Returns a *NotFoundError when no ChatGroups ID was found.
func (_q *ChatGroupsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatgroups.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *ChatGroupsQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatGroups entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatGroups entity is found.
// Returns a *NotFoundError when no ChatGroups entities are found.
func (_q *ChatGroupsQuery) Only(ctx context.Context) (*ChatGroups, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatgroups.Label}
	default:
		return nil, &NotSingularError{chatgroups.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *ChatGroupsQuery) OnlyX(ctx context.Context) *ChatGroups {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatGroups ID in the query.
// Returns a *NotSingularError when more than one ChatGroups ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *ChatGroupsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatgroups.Label}
	default:
		err = &NotSingularError{chatgroups.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *ChatGroupsQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatGroupsSlice.
func (_q *ChatGroupsQuery) All(ctx context.Context) ([]*ChatGroups, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatGroups, *ChatGroupsQuery]()
	return withInterceptors[[]*ChatGroups](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *ChatGroupsQuery) AllX(ctx context.Context) []*ChatGroups {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatGroups IDs.
func (_q *ChatGroupsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(chatgroups.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *ChatGroupsQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *ChatGroupsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*ChatGroupsQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *ChatGroupsQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *ChatGroupsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *ChatGroupsQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatGroupsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *ChatGroupsQuery) Clone() *ChatGroupsQuery {
	if _q == nil {
		return nil
	}
	return &ChatGroupsQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]chatgroups.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.ChatGroups{}, _q.predicates...),
		withUsers:            _q.withUsers.Clone(),
		withChatGroupMembers: _q.withChatGroupMembers.Clone(),
		withChatMessages:     _q.withChatMessages.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUsers tells the query-builder to eager-load the nodes that are connected to
// the "Users" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatGroupsQuery) WithUsers(opts ...func(*UsersQuery)) *ChatGroupsQuery {
	query := (&UsersClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUsers = query
	return _q
}

// WithChatGroupMembers tells the query-builder to eager-load the nodes that are connected to
// the "ChatGroupMembers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatGroupsQuery) WithChatGroupMembers(opts ...func(*ChatGroupMembersQuery)) *ChatGroupsQuery {
	query := (&ChatGroupMembersClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChatGroupMembers = query
	return _q
}

// WithChatMessages tells the query-builder to eager-load the nodes that are connected to
// the "ChatMessages" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *ChatGroupsQuery) WithChatMessages(opts ...func(*ChatMessagesQuery)) *ChatGroupsQuery {
	query := (&ChatMessagesClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withChatMessages = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deletedAt"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatGroups.Query().
//		GroupBy(chatgroups.FieldDeletedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *ChatGroupsQuery) GroupBy(field string, fields ...string) *ChatGroupsGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatGroupsGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = chatgroups.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DeletedAt time.Time `json:"deletedAt"`
//	}
//
//	client.ChatGroups.Query().
//		Select(chatgroups.FieldDeletedAt).
//		Scan(ctx, &v)
func (_q *ChatGroupsQuery) Select(fields ...string) *ChatGroupsSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &ChatGroupsSelect{ChatGroupsQuery: _q}
	sbuild.label = chatgroups.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatGroupsSelect configured with the given aggregations.
func (_q *ChatGroupsQuery) Aggregate(fns ...AggregateFunc) *ChatGroupsSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *ChatGroupsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !chatgroups.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *ChatGroupsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatGroups, error) {
	var (
		nodes       = []*ChatGroups{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withUsers != nil,
			_q.withChatGroupMembers != nil,
			_q.withChatMessages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatGroups).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatGroups{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUsers; query != nil {
		if err := _q.loadUsers(ctx, query, nodes, nil,
			func(n *ChatGroups, e *Users) { n.Edges.Users = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withChatGroupMembers; query != nil {
		if err := _q.loadChatGroupMembers(ctx, query, nodes,
			func(n *ChatGroups) { n.Edges.ChatGroupMembers = []*ChatGroupMembers{} },
			func(n *ChatGroups, e *ChatGroupMembers) {
				n.Edges.ChatGroupMembers = append(n.Edges.ChatGroupMembers, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := _q.withChatMessages; query != nil {
		if err := _q.loadChatMessages(ctx, query, nodes,
			func(n *ChatGroups) { n.Edges.ChatMessages = []*ChatMessages{} },
			func(n *ChatGroups, e *ChatMessages) { n.Edges.ChatMessages = append(n.Edges.ChatMessages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *ChatGroupsQuery) loadUsers(ctx context.Context, query *UsersQuery, nodes []*ChatGroups, init func(*ChatGroups), assign func(*ChatGroups, *Users)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ChatGroups)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(users.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *ChatGroupsQuery) loadChatGroupMembers(ctx context.Context, query *ChatGroupMembersQuery, nodes []*ChatGroups, init func(*ChatGroups), assign func(*ChatGroups, *ChatGroupMembers)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ChatGroups)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(chatgroupmembers.FieldChatGroupID)
	}
	query.Where(predicate.ChatGroupMembers(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(chatgroups.ChatGroupMembersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChatGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "chat_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *ChatGroupsQuery) loadChatMessages(ctx context.Context, query *ChatMessagesQuery, nodes []*ChatGroups, init func(*ChatGroups), assign func(*ChatGroups, *ChatMessages)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*ChatGroups)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(chatmessages.FieldChatGroupID)
	}
	query.Where(predicate.ChatMessages(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(chatgroups.ChatMessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ChatGroupID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "chat_group_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *ChatGroupsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *ChatGroupsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatgroups.Table, chatgroups.Columns, sqlgraph.NewFieldSpec(chatgroups.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatgroups.FieldID)
		for i := range fields {
			if fields[i] != chatgroups.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUsers != nil {
			_spec.Node.AddColumnOnce(chatgroups.FieldUserID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *ChatGroupsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(chatgroups.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = chatgroups.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatGroupsGroupBy is the group-by builder for ChatGroups entities.
type ChatGroupsGroupBy struct {
	selector
	build *ChatGroupsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *ChatGroupsGroupBy) Aggregate(fns ...AggregateFunc) *ChatGroupsGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *ChatGroupsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatGroupsQuery, *ChatGroupsGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *ChatGroupsGroupBy) sqlScan(ctx context.Context, root *ChatGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatGroupsSelect is the builder for selecting fields of ChatGroups entities.
type ChatGroupsSelect struct {
	*ChatGroupsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *ChatGroupsSelect) Aggregate(fns ...AggregateFunc) *ChatGroupsSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *ChatGroupsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatGroupsQuery, *ChatGroupsSelect](ctx, _s.ChatGroupsQuery, _s, _s.inters, v)
}

func (_s *ChatGroupsSelect) sqlScan(ctx context.Context, root *ChatGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
