// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"go-backend/ent/migrate"

	"go-backend/ent/articles"
	"go-backend/ent/foods"
	"go-backend/ent/orders"
	"go-backend/ent/users"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"

	stdsql "database/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Articles is the client for interacting with the Articles builders.
	Articles *ArticlesClient
	// Foods is the client for interacting with the Foods builders.
	Foods *FoodsClient
	// Orders is the client for interacting with the Orders builders.
	Orders *OrdersClient
	// Users is the client for interacting with the Users builders.
	Users *UsersClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Articles = NewArticlesClient(c.config)
	c.Foods = NewFoodsClient(c.config)
	c.Orders = NewOrdersClient(c.config)
	c.Users = NewUsersClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Articles: NewArticlesClient(cfg),
		Foods:    NewFoodsClient(cfg),
		Orders:   NewOrdersClient(cfg),
		Users:    NewUsersClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:      ctx,
		config:   cfg,
		Articles: NewArticlesClient(cfg),
		Foods:    NewFoodsClient(cfg),
		Orders:   NewOrdersClient(cfg),
		Users:    NewUsersClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Articles.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Articles.Use(hooks...)
	c.Foods.Use(hooks...)
	c.Orders.Use(hooks...)
	c.Users.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Articles.Intercept(interceptors...)
	c.Foods.Intercept(interceptors...)
	c.Orders.Intercept(interceptors...)
	c.Users.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ArticlesMutation:
		return c.Articles.mutate(ctx, m)
	case *FoodsMutation:
		return c.Foods.mutate(ctx, m)
	case *OrdersMutation:
		return c.Orders.mutate(ctx, m)
	case *UsersMutation:
		return c.Users.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ArticlesClient is a client for the Articles schema.
type ArticlesClient struct {
	config
}

// NewArticlesClient returns a client for the Articles from the given config.
func NewArticlesClient(c config) *ArticlesClient {
	return &ArticlesClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `articles.Hooks(f(g(h())))`.
func (c *ArticlesClient) Use(hooks ...Hook) {
	c.hooks.Articles = append(c.hooks.Articles, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `articles.Intercept(f(g(h())))`.
func (c *ArticlesClient) Intercept(interceptors ...Interceptor) {
	c.inters.Articles = append(c.inters.Articles, interceptors...)
}

// Create returns a builder for creating a Articles entity.
func (c *ArticlesClient) Create() *ArticlesCreate {
	mutation := newArticlesMutation(c.config, OpCreate)
	return &ArticlesCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Articles entities.
func (c *ArticlesClient) CreateBulk(builders ...*ArticlesCreate) *ArticlesCreateBulk {
	return &ArticlesCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ArticlesClient) MapCreateBulk(slice any, setFunc func(*ArticlesCreate, int)) *ArticlesCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ArticlesCreateBulk{err: fmt.Errorf("calling to ArticlesClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ArticlesCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ArticlesCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Articles.
func (c *ArticlesClient) Update() *ArticlesUpdate {
	mutation := newArticlesMutation(c.config, OpUpdate)
	return &ArticlesUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ArticlesClient) UpdateOne(_m *Articles) *ArticlesUpdateOne {
	mutation := newArticlesMutation(c.config, OpUpdateOne, withArticles(_m))
	return &ArticlesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ArticlesClient) UpdateOneID(id int) *ArticlesUpdateOne {
	mutation := newArticlesMutation(c.config, OpUpdateOne, withArticlesID(id))
	return &ArticlesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Articles.
func (c *ArticlesClient) Delete() *ArticlesDelete {
	mutation := newArticlesMutation(c.config, OpDelete)
	return &ArticlesDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ArticlesClient) DeleteOne(_m *Articles) *ArticlesDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ArticlesClient) DeleteOneID(id int) *ArticlesDeleteOne {
	builder := c.Delete().Where(articles.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ArticlesDeleteOne{builder}
}

// Query returns a query builder for Articles.
func (c *ArticlesClient) Query() *ArticlesQuery {
	return &ArticlesQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeArticles},
		inters: c.Interceptors(),
	}
}

// Get returns a Articles entity by its id.
func (c *ArticlesClient) Get(ctx context.Context, id int) (*Articles, error) {
	return c.Query().Where(articles.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ArticlesClient) GetX(ctx context.Context, id int) *Articles {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryUsers queries the Users edge of a Articles.
func (c *ArticlesClient) QueryUsers(_m *Articles) *UsersQuery {
	query := (&UsersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(articles.Table, articles.FieldID, id),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, articles.UsersTable, articles.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ArticlesClient) Hooks() []Hook {
	hooks := c.hooks.Articles
	return append(hooks[:len(hooks):len(hooks)], articles.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *ArticlesClient) Interceptors() []Interceptor {
	inters := c.inters.Articles
	return append(inters[:len(inters):len(inters)], articles.Interceptors[:]...)
}

func (c *ArticlesClient) mutate(ctx context.Context, m *ArticlesMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ArticlesCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ArticlesUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ArticlesUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ArticlesDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Articles mutation op: %q", m.Op())
	}
}

// FoodsClient is a client for the Foods schema.
type FoodsClient struct {
	config
}

// NewFoodsClient returns a client for the Foods from the given config.
func NewFoodsClient(c config) *FoodsClient {
	return &FoodsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `foods.Hooks(f(g(h())))`.
func (c *FoodsClient) Use(hooks ...Hook) {
	c.hooks.Foods = append(c.hooks.Foods, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `foods.Intercept(f(g(h())))`.
func (c *FoodsClient) Intercept(interceptors ...Interceptor) {
	c.inters.Foods = append(c.inters.Foods, interceptors...)
}

// Create returns a builder for creating a Foods entity.
func (c *FoodsClient) Create() *FoodsCreate {
	mutation := newFoodsMutation(c.config, OpCreate)
	return &FoodsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Foods entities.
func (c *FoodsClient) CreateBulk(builders ...*FoodsCreate) *FoodsCreateBulk {
	return &FoodsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *FoodsClient) MapCreateBulk(slice any, setFunc func(*FoodsCreate, int)) *FoodsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &FoodsCreateBulk{err: fmt.Errorf("calling to FoodsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*FoodsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &FoodsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Foods.
func (c *FoodsClient) Update() *FoodsUpdate {
	mutation := newFoodsMutation(c.config, OpUpdate)
	return &FoodsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *FoodsClient) UpdateOne(_m *Foods) *FoodsUpdateOne {
	mutation := newFoodsMutation(c.config, OpUpdateOne, withFoods(_m))
	return &FoodsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *FoodsClient) UpdateOneID(id int) *FoodsUpdateOne {
	mutation := newFoodsMutation(c.config, OpUpdateOne, withFoodsID(id))
	return &FoodsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Foods.
func (c *FoodsClient) Delete() *FoodsDelete {
	mutation := newFoodsMutation(c.config, OpDelete)
	return &FoodsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *FoodsClient) DeleteOne(_m *Foods) *FoodsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *FoodsClient) DeleteOneID(id int) *FoodsDeleteOne {
	builder := c.Delete().Where(foods.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &FoodsDeleteOne{builder}
}

// Query returns a query builder for Foods.
func (c *FoodsClient) Query() *FoodsQuery {
	return &FoodsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeFoods},
		inters: c.Interceptors(),
	}
}

// Get returns a Foods entity by its id.
func (c *FoodsClient) Get(ctx context.Context, id int) (*Foods, error) {
	return c.Query().Where(foods.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *FoodsClient) GetX(ctx context.Context, id int) *Foods {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOrders queries the Orders edge of a Foods.
func (c *FoodsClient) QueryOrders(_m *Foods) *OrdersQuery {
	query := (&OrdersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(foods.Table, foods.FieldID, id),
			sqlgraph.To(orders.Table, orders.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, foods.OrdersTable, foods.OrdersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *FoodsClient) Hooks() []Hook {
	hooks := c.hooks.Foods
	return append(hooks[:len(hooks):len(hooks)], foods.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *FoodsClient) Interceptors() []Interceptor {
	inters := c.inters.Foods
	return append(inters[:len(inters):len(inters)], foods.Interceptors[:]...)
}

func (c *FoodsClient) mutate(ctx context.Context, m *FoodsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&FoodsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&FoodsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&FoodsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&FoodsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Foods mutation op: %q", m.Op())
	}
}

// OrdersClient is a client for the Orders schema.
type OrdersClient struct {
	config
}

// NewOrdersClient returns a client for the Orders from the given config.
func NewOrdersClient(c config) *OrdersClient {
	return &OrdersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `orders.Hooks(f(g(h())))`.
func (c *OrdersClient) Use(hooks ...Hook) {
	c.hooks.Orders = append(c.hooks.Orders, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `orders.Intercept(f(g(h())))`.
func (c *OrdersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Orders = append(c.inters.Orders, interceptors...)
}

// Create returns a builder for creating a Orders entity.
func (c *OrdersClient) Create() *OrdersCreate {
	mutation := newOrdersMutation(c.config, OpCreate)
	return &OrdersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Orders entities.
func (c *OrdersClient) CreateBulk(builders ...*OrdersCreate) *OrdersCreateBulk {
	return &OrdersCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrdersClient) MapCreateBulk(slice any, setFunc func(*OrdersCreate, int)) *OrdersCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrdersCreateBulk{err: fmt.Errorf("calling to OrdersClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrdersCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrdersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Orders.
func (c *OrdersClient) Update() *OrdersUpdate {
	mutation := newOrdersMutation(c.config, OpUpdate)
	return &OrdersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrdersClient) UpdateOne(_m *Orders) *OrdersUpdateOne {
	mutation := newOrdersMutation(c.config, OpUpdateOne, withOrders(_m))
	return &OrdersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrdersClient) UpdateOneID(id int) *OrdersUpdateOne {
	mutation := newOrdersMutation(c.config, OpUpdateOne, withOrdersID(id))
	return &OrdersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Orders.
func (c *OrdersClient) Delete() *OrdersDelete {
	mutation := newOrdersMutation(c.config, OpDelete)
	return &OrdersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrdersClient) DeleteOne(_m *Orders) *OrdersDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrdersClient) DeleteOneID(id int) *OrdersDeleteOne {
	builder := c.Delete().Where(orders.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrdersDeleteOne{builder}
}

// Query returns a query builder for Orders.
func (c *OrdersClient) Query() *OrdersQuery {
	return &OrdersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrders},
		inters: c.Interceptors(),
	}
}

// Get returns a Orders entity by its id.
func (c *OrdersClient) Get(ctx context.Context, id int) (*Orders, error) {
	return c.Query().Where(orders.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrdersClient) GetX(ctx context.Context, id int) *Orders {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryFoods queries the Foods edge of a Orders.
func (c *OrdersClient) QueryFoods(_m *Orders) *FoodsQuery {
	query := (&FoodsClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orders.Table, orders.FieldID, id),
			sqlgraph.To(foods.Table, foods.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orders.FoodsTable, orders.FoodsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryUsers queries the Users edge of a Orders.
func (c *OrdersClient) QueryUsers(_m *Orders) *UsersQuery {
	query := (&UsersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orders.Table, orders.FieldID, id),
			sqlgraph.To(users.Table, users.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orders.UsersTable, orders.UsersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrdersClient) Hooks() []Hook {
	hooks := c.hooks.Orders
	return append(hooks[:len(hooks):len(hooks)], orders.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *OrdersClient) Interceptors() []Interceptor {
	inters := c.inters.Orders
	return append(inters[:len(inters):len(inters)], orders.Interceptors[:]...)
}

func (c *OrdersClient) mutate(ctx context.Context, m *OrdersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrdersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrdersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrdersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrdersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Orders mutation op: %q", m.Op())
	}
}

// UsersClient is a client for the Users schema.
type UsersClient struct {
	config
}

// NewUsersClient returns a client for the Users from the given config.
func NewUsersClient(c config) *UsersClient {
	return &UsersClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `users.Hooks(f(g(h())))`.
func (c *UsersClient) Use(hooks ...Hook) {
	c.hooks.Users = append(c.hooks.Users, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `users.Intercept(f(g(h())))`.
func (c *UsersClient) Intercept(interceptors ...Interceptor) {
	c.inters.Users = append(c.inters.Users, interceptors...)
}

// Create returns a builder for creating a Users entity.
func (c *UsersClient) Create() *UsersCreate {
	mutation := newUsersMutation(c.config, OpCreate)
	return &UsersCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Users entities.
func (c *UsersClient) CreateBulk(builders ...*UsersCreate) *UsersCreateBulk {
	return &UsersCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UsersClient) MapCreateBulk(slice any, setFunc func(*UsersCreate, int)) *UsersCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UsersCreateBulk{err: fmt.Errorf("calling to UsersClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UsersCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UsersCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Users.
func (c *UsersClient) Update() *UsersUpdate {
	mutation := newUsersMutation(c.config, OpUpdate)
	return &UsersUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UsersClient) UpdateOne(_m *Users) *UsersUpdateOne {
	mutation := newUsersMutation(c.config, OpUpdateOne, withUsers(_m))
	return &UsersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UsersClient) UpdateOneID(id int) *UsersUpdateOne {
	mutation := newUsersMutation(c.config, OpUpdateOne, withUsersID(id))
	return &UsersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Users.
func (c *UsersClient) Delete() *UsersDelete {
	mutation := newUsersMutation(c.config, OpDelete)
	return &UsersDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UsersClient) DeleteOne(_m *Users) *UsersDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UsersClient) DeleteOneID(id int) *UsersDeleteOne {
	builder := c.Delete().Where(users.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UsersDeleteOne{builder}
}

// Query returns a query builder for Users.
func (c *UsersClient) Query() *UsersQuery {
	return &UsersQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUsers},
		inters: c.Interceptors(),
	}
}

// Get returns a Users entity by its id.
func (c *UsersClient) Get(ctx context.Context, id int) (*Users, error) {
	return c.Query().Where(users.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UsersClient) GetX(ctx context.Context, id int) *Users {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryArticles queries the Articles edge of a Users.
func (c *UsersClient) QueryArticles(_m *Users) *ArticlesQuery {
	query := (&ArticlesClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(users.Table, users.FieldID, id),
			sqlgraph.To(articles.Table, articles.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, users.ArticlesTable, users.ArticlesColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrders queries the Orders edge of a Users.
func (c *UsersClient) QueryOrders(_m *Users) *OrdersQuery {
	query := (&OrdersClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(users.Table, users.FieldID, id),
			sqlgraph.To(orders.Table, orders.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, users.OrdersTable, users.OrdersColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *UsersClient) Hooks() []Hook {
	hooks := c.hooks.Users
	return append(hooks[:len(hooks):len(hooks)], users.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *UsersClient) Interceptors() []Interceptor {
	inters := c.inters.Users
	return append(inters[:len(inters):len(inters)], users.Interceptors[:]...)
}

func (c *UsersClient) mutate(ctx context.Context, m *UsersMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UsersCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UsersUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UsersUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UsersDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Users mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Articles, Foods, Orders, Users []ent.Hook
	}
	inters struct {
		Articles, Foods, Orders, Users []ent.Interceptor
	}
)

// ExecContext allows calling the underlying ExecContext method of the driver if it is supported by it.
// See, database/sql#DB.ExecContext for more information.
func (c *config) ExecContext(ctx context.Context, query string, args ...any) (stdsql.Result, error) {
	ex, ok := c.driver.(interface {
		ExecContext(context.Context, string, ...any) (stdsql.Result, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.ExecContext is not supported")
	}
	return ex.ExecContext(ctx, query, args...)
}

// QueryContext allows calling the underlying QueryContext method of the driver if it is supported by it.
// See, database/sql#DB.QueryContext for more information.
func (c *config) QueryContext(ctx context.Context, query string, args ...any) (*stdsql.Rows, error) {
	q, ok := c.driver.(interface {
		QueryContext(context.Context, string, ...any) (*stdsql.Rows, error)
	})
	if !ok {
		return nil, fmt.Errorf("Driver.QueryContext is not supported")
	}
	return q.QueryContext(ctx, query, args...)
}
