// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/foods"
	"go-backend/ent/orders"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrdersCreate is the builder for creating a Orders entity.
type OrdersCreate struct {
	config
	mutation *OrdersMutation
	hooks    []Hook
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *OrdersCreate) SetDeletedAt(v time.Time) *OrdersCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *OrdersCreate) SetNillableDeletedAt(v *time.Time) *OrdersCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *OrdersCreate) SetUserID(v int) *OrdersCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetFoodID sets the "food_id" field.
func (_c *OrdersCreate) SetFoodID(v int) *OrdersCreate {
	_c.mutation.SetFoodID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OrdersCreate) SetCreatedAt(v time.Time) *OrdersCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OrdersCreate) SetNillableCreatedAt(v *time.Time) *OrdersCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OrdersCreate) SetUpdatedAt(v time.Time) *OrdersCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OrdersCreate) SetNillableUpdatedAt(v *time.Time) *OrdersCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetFoodsID sets the "Foods" edge to the Foods entity by ID.
func (_c *OrdersCreate) SetFoodsID(id int) *OrdersCreate {
	_c.mutation.SetFoodsID(id)
	return _c
}

// SetFoods sets the "Foods" edge to the Foods entity.
func (_c *OrdersCreate) SetFoods(v *Foods) *OrdersCreate {
	return _c.SetFoodsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_c *OrdersCreate) SetUsersID(id int) *OrdersCreate {
	_c.mutation.SetUsersID(id)
	return _c
}

// SetUsers sets the "Users" edge to the Users entity.
func (_c *OrdersCreate) SetUsers(v *Users) *OrdersCreate {
	return _c.SetUsersID(v.ID)
}

// Mutation returns the OrdersMutation object of the builder.
func (_c *OrdersCreate) Mutation() *OrdersMutation {
	return _c.mutation
}

// Save creates the Orders in the database.
func (_c *OrdersCreate) Save(ctx context.Context) (*Orders, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrdersCreate) SaveX(ctx context.Context) *Orders {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrdersCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrdersCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrdersCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if orders.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized orders.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := orders.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if orders.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orders.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orders.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrdersCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Orders.user_id"`)}
	}
	if _, ok := _c.mutation.FoodID(); !ok {
		return &ValidationError{Name: "food_id", err: errors.New(`ent: missing required field "Orders.food_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Orders.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Orders.updated_at"`)}
	}
	if len(_c.mutation.FoodsIDs()) == 0 {
		return &ValidationError{Name: "Foods", err: errors.New(`ent: missing required edge "Orders.Foods"`)}
	}
	if len(_c.mutation.UsersIDs()) == 0 {
		return &ValidationError{Name: "Users", err: errors.New(`ent: missing required edge "Orders.Users"`)}
	}
	return nil
}

func (_c *OrdersCreate) sqlSave(ctx context.Context) (*Orders, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrdersCreate) createSpec() (*Orders, *sqlgraph.CreateSpec) {
	var (
		_node = &Orders{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orders.Table, sqlgraph.NewFieldSpec(orders.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(orders.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(orders.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(orders.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.FoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.FoodsTable,
			Columns: []string{orders.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(foods.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FoodID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.UsersTable,
			Columns: []string{orders.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrdersCreateBulk is the builder for creating many Orders entities in bulk.
type OrdersCreateBulk struct {
	config
	err      error
	builders []*OrdersCreate
}

// Save creates the Orders entities in the database.
func (_c *OrdersCreateBulk) Save(ctx context.Context) ([]*Orders, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Orders, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrdersMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrdersCreateBulk) SaveX(ctx context.Context) []*Orders {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrdersCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrdersCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
