// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/ent/foods"
	"go-backend/ent/orders"
	"go-backend/ent/predicate"
	"go-backend/ent/users"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OrdersUpdate is the builder for updating Orders entities.
type OrdersUpdate struct {
	config
	hooks    []Hook
	mutation *OrdersMutation
}

// Where appends a list predicates to the OrdersUpdate builder.
func (_u *OrdersUpdate) Where(ps ...predicate.Orders) *OrdersUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrdersUpdate) SetDeletedAt(v time.Time) *OrdersUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrdersUpdate) SetNillableDeletedAt(v *time.Time) *OrdersUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrdersUpdate) ClearDeletedAt() *OrdersUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrdersUpdate) SetUserID(v int) *OrdersUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrdersUpdate) SetNillableUserID(v *int) *OrdersUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFoodID sets the "food_id" field.
func (_u *OrdersUpdate) SetFoodID(v int) *OrdersUpdate {
	_u.mutation.SetFoodID(v)
	return _u
}

// SetNillableFoodID sets the "food_id" field if the given value is not nil.
func (_u *OrdersUpdate) SetNillableFoodID(v *int) *OrdersUpdate {
	if v != nil {
		_u.SetFoodID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrdersUpdate) SetUpdatedAt(v time.Time) *OrdersUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFoodsID sets the "Foods" edge to the Foods entity by ID.
func (_u *OrdersUpdate) SetFoodsID(id int) *OrdersUpdate {
	_u.mutation.SetFoodsID(id)
	return _u
}

// SetFoods sets the "Foods" edge to the Foods entity.
func (_u *OrdersUpdate) SetFoods(v *Foods) *OrdersUpdate {
	return _u.SetFoodsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *OrdersUpdate) SetUsersID(id int) *OrdersUpdate {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *OrdersUpdate) SetUsers(v *Users) *OrdersUpdate {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the OrdersMutation object of the builder.
func (_u *OrdersUpdate) Mutation() *OrdersMutation {
	return _u.mutation
}

// ClearFoods clears the "Foods" edge to the Foods entity.
func (_u *OrdersUpdate) ClearFoods() *OrdersUpdate {
	_u.mutation.ClearFoods()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *OrdersUpdate) ClearUsers() *OrdersUpdate {
	_u.mutation.ClearUsers()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrdersUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrdersUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrdersUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrdersUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrdersUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if orders.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orders.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orders.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrdersUpdate) check() error {
	if _u.mutation.FoodsCleared() && len(_u.mutation.FoodsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Orders.Foods"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Orders.Users"`)
	}
	return nil
}

func (_u *OrdersUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orders.Table, orders.Columns, sqlgraph.NewFieldSpec(orders.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(orders.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(orders.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orders.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FoodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.FoodsTable,
			Columns: []string{orders.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(foods.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.FoodsTable,
			Columns: []string{orders.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(foods.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.UsersTable,
			Columns: []string{orders.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.UsersTable,
			Columns: []string{orders.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrdersUpdateOne is the builder for updating a single Orders entity.
type OrdersUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrdersMutation
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrdersUpdateOne) SetDeletedAt(v time.Time) *OrdersUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrdersUpdateOne) SetNillableDeletedAt(v *time.Time) *OrdersUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrdersUpdateOne) ClearDeletedAt() *OrdersUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OrdersUpdateOne) SetUserID(v int) *OrdersUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OrdersUpdateOne) SetNillableUserID(v *int) *OrdersUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetFoodID sets the "food_id" field.
func (_u *OrdersUpdateOne) SetFoodID(v int) *OrdersUpdateOne {
	_u.mutation.SetFoodID(v)
	return _u
}

// SetNillableFoodID sets the "food_id" field if the given value is not nil.
func (_u *OrdersUpdateOne) SetNillableFoodID(v *int) *OrdersUpdateOne {
	if v != nil {
		_u.SetFoodID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrdersUpdateOne) SetUpdatedAt(v time.Time) *OrdersUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFoodsID sets the "Foods" edge to the Foods entity by ID.
func (_u *OrdersUpdateOne) SetFoodsID(id int) *OrdersUpdateOne {
	_u.mutation.SetFoodsID(id)
	return _u
}

// SetFoods sets the "Foods" edge to the Foods entity.
func (_u *OrdersUpdateOne) SetFoods(v *Foods) *OrdersUpdateOne {
	return _u.SetFoodsID(v.ID)
}

// SetUsersID sets the "Users" edge to the Users entity by ID.
func (_u *OrdersUpdateOne) SetUsersID(id int) *OrdersUpdateOne {
	_u.mutation.SetUsersID(id)
	return _u
}

// SetUsers sets the "Users" edge to the Users entity.
func (_u *OrdersUpdateOne) SetUsers(v *Users) *OrdersUpdateOne {
	return _u.SetUsersID(v.ID)
}

// Mutation returns the OrdersMutation object of the builder.
func (_u *OrdersUpdateOne) Mutation() *OrdersMutation {
	return _u.mutation
}

// ClearFoods clears the "Foods" edge to the Foods entity.
func (_u *OrdersUpdateOne) ClearFoods() *OrdersUpdateOne {
	_u.mutation.ClearFoods()
	return _u
}

// ClearUsers clears the "Users" edge to the Users entity.
func (_u *OrdersUpdateOne) ClearUsers() *OrdersUpdateOne {
	_u.mutation.ClearUsers()
	return _u
}

// Where appends a list predicates to the OrdersUpdate builder.
func (_u *OrdersUpdateOne) Where(ps ...predicate.Orders) *OrdersUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrdersUpdateOne) Select(field string, fields ...string) *OrdersUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Orders entity.
func (_u *OrdersUpdateOne) Save(ctx context.Context) (*Orders, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrdersUpdateOne) SaveX(ctx context.Context) *Orders {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrdersUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrdersUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrdersUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if orders.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized orders.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := orders.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrdersUpdateOne) check() error {
	if _u.mutation.FoodsCleared() && len(_u.mutation.FoodsIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Orders.Foods"`)
	}
	if _u.mutation.UsersCleared() && len(_u.mutation.UsersIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Orders.Users"`)
	}
	return nil
}

func (_u *OrdersUpdateOne) sqlSave(ctx context.Context) (_node *Orders, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orders.Table, orders.Columns, sqlgraph.NewFieldSpec(orders.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Orders.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orders.FieldID)
		for _, f := range fields {
			if !orders.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orders.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(orders.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(orders.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(orders.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.FoodsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.FoodsTable,
			Columns: []string{orders.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(foods.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FoodsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.FoodsTable,
			Columns: []string{orders.FoodsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(foods.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.UsersTable,
			Columns: []string{orders.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orders.UsersTable,
			Columns: []string{orders.UsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(users.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Orders{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orders.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
