// Code generated by entimport, DO NOT EDIT.

package schema

import (
	softdelete "go-backend/ent/soft-delete"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Foods struct {
	ent.Schema
}

func (Foods) Fields() []ent.Field {
	return []ent.Field{
		field.String("name"),
		field.String("description").Optional(),

		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}

}
func (Foods) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Orders", Orders.Type),
	}
}

func (Foods) Mixin() []ent.Mixin {
	return []ent.Mixin{
		softdelete.SoftDeleteMixin{},
	}
}
