// Code generated by entimport, DO NOT EDIT.

package schema

import (
	softdelete "go-backend/ent/soft-delete"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Users struct {
	ent.Schema
}

func (Users) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").Unique(),
		field.String("full_name").Optional().Nillable().StructTag(`json:"fullName"`),
		field.String("avatar").Optional().Nillable().StructTag(`json:"avatar"`),
		field.String("password").Optional().Nillable().Sensitive(),
		field.String("totp_secret").Optional().Nillable().Sensitive(),
		field.String("google_id").Optional().Nillable().Sensitive(),

		field.Time("created_at").Default(time.Now).Immutable().StructTag(`json:"createdAt"`),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now).StructTag(`json:"updatedAt"`),
	}
}
func (Users) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Articles", Articles.Type),
		edge.To("Orders", Orders.Type),
		edge.To("ChatGroups", ChatGroups.Type),
		edge.To("ChatGroupMembers", ChatGroupMembers.Type),
		edge.To("ChatMessages", ChatMessages.Type),
	}
}

func (Users) Mixin() []ent.Mixin {
	return []ent.Mixin{
		softdelete.SoftDeleteMixin{},
	}
}
