// Code generated by entimport, DO NOT EDIT.

package schema

import (
	softdelete "go-backend/ent/soft-delete"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/schema/edge"
	"entgo.io/ent/schema/field"
)

type Users struct {
	ent.Schema
}

func (Users) Fields() []ent.Field {
	return []ent.Field{
		field.String("email").Unique(),
		field.String("full_name").Optional(),
		field.String("avatar").Optional(),
		field.String("password").Optional(),
		field.String("totp_secret").Optional(),
		field.String("google_id").Optional(),

		field.Time("created_at").Default(time.Now).Immutable(),
		field.Time("updated_at").Default(time.Now).UpdateDefault(time.Now),
	}
}
func (Users) Edges() []ent.Edge {
	return []ent.Edge{
		edge.To("Articles", Articles.Type),
		edge.To("Orders", Orders.Type),
	}
}

func (Users) Mixin() []ent.Mixin {
	return []ent.Mixin{
		softdelete.SoftDeleteMixin{},
	}
}
