name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Setup SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
            
            - name: Trust deploy host
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan -H "${{ secrets.SERVER_HOST }}" >> ~/.ssh/known_hosts

            - name: Build Docker image
              run: |
                  docker build -t img-go-backend:latest .

            - name: Transfer Docker image to server
              run: |
                  docker save img-go-backend:latest | gzip | ssh "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" "gunzip | sudo docker load"

            - name: Install Atlas
              uses: ariga/setup-atlas@v0

            - name: Run migration
              run: |
                  ssh -fN \
                  -L 3307:127.0.0.1:3306 \
                  "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" 

                  atlas migrate apply \
                  --dir "file://${GITHUB_WORKSPACE}/ent/migrate/migrations" \
                  --url "${{ secrets.DATABASE_URL }}"

            - name: restart services
              run: |
                  ssh "${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}" << 'EOF'
                    set -e

                    cd /home/ubuntu/go-backend

                    sudo docker compose --env-file .env.production up -d

                    sudo docker image prune -f || true
                    sudo docker builder prune -f || true
                  EOF
