// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Articles is the predicate function for articles builders.
type Articles func(*sql.Selector)

// ChatGroupMembers is the predicate function for chatgroupmembers builders.
type ChatGroupMembers func(*sql.Selector)

// ChatGroups is the predicate function for chatgroups builders.
type ChatGroups func(*sql.Selector)

// ChatMessages is the predicate function for chatmessages builders.
type ChatMessages func(*sql.Selector)

// Foods is the predicate function for foods builders.
type Foods func(*sql.Selector)

// Orders is the predicate function for orders builders.
type Orders func(*sql.Selector)

// Users is the predicate function for users builders.
type Users func(*sql.Selector)
